"""Allowed All field in File table set default False

Revision ID: 7c580d8e68c7
Revises: 56e5bba4226e
Create Date: 2024-06-20 14:32:37.918322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c580d8e68c7'
down_revision = '56e5bba4226e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
