"""Add Company, Department, Position and relationship between tables

Revision ID: f3405d4d7241
Revises: d6910d62ef15
Create Date: 2024-04-11 15:04:17.512407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3405d4d7241'
down_revision = 'd6910d62ef15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
